version: '3'

services:
  nginx:
    image: "nginx:latest"

    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/usr/share/nginx/html/
      - ./nginx:/etc/nginx/conf.d

    links:
      - "php-fpm"

  php-fpm:
    image: "bitnami/php-fpm"
    container_name: "php-fpm"
    volumes:
      - ./app:/app

