version: '3'

services:
  nginx:
    image: "nginx:latest"

    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/usr/share/nginx/html/
      - ./nginx:/etc/nginx/conf.d

  php-fpm:
    image: "php:7.2-fpm"
    container_name: "php-fpm"
    volumes:
      - ./app:/app

