version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/share/nginx/html/
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/

  php-fpm:
    build: ./php-fpm
    volumes:
      - ./app:/app
    env_file:
      - php-fpm/.env

  pgsql:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=camagru
      - POSTGRES_USER=camagru
      - POSTGRES_PASSWORD=camagru
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./db_dump:/db_dump




